// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"test_demo/rpc/internal/logic"
	"test_demo/rpc/internal/svc"
	"test_demo/rpc/order"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServiceServer) GetUser(ctx context.Context, in *order.GetUserRequest) (*order.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
