// Code generated by goctl. DO NOT EDIT.
package types

type UserOrderRequest struct {
	UserId      int `json:"user_id"`
	ProductId   int `json:"product_id"`
	OrderAmount int `json:"order_amount"`
	OrderId     int `json:"order_id"`
	Action      int `json:"action"`
}

type MultiOrderRequest struct {
	UserId      []int `json:"user_id"`
	ProductId   int   `json:"product_id"`
	OrderAmount int   `json:"order_amount"`
	Action      int   `json:"action"`
}

type GetUserRequest struct {
	UserId int `form:"user_id"`
}

type UserOrder struct {
	OrderId       int `json:"order_id"`
	UserId        int `json:"user_id"`
	ProductId     int `json:"product_id"`
	StockQuantity int `json:"stock_quantity"`
	OrderTime     int `json:"order_time"`
	OrderStaus    int `json:"order_status"`
	OrderAmount   int `json:"order_amount"`
}

type UserRow struct {
	UserId   int    `json:"user_id"`
	UserName string `json:"user_name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UserOrderResponse struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data UserOrder `json:"data"`
}

type MultiOrderResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data []UserOrder `json:"data"`
}

type GetUserResponse struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Data UserRow `json:"data"`
}
