// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"test_demo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/user",
				Handler: UserOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/multi",
				Handler: MultiOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: GetUserHandler(serverCtx),
			},
		},
	)
}
